import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Footer } from "../components/layout/Footer";
import { Navbar } from "../components/layout/Navbar";
import { Toaster } from "react-hot-toast";
import { useUser } from "../services/useUser";
import { useEffect } from "react";
import { useRouter } from "next/navigation";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700", "600"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en" data-theme="daCodes">
      <head>
        <title>Prueba tecnica - Almer Ibarra  </title>
      </head>
      <body className={`min-h-screen ${poppins.className}`}>
        <Toaster />
        <Navbar />
        <div className="p-8 md:p-24">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
